version: "3"
services:
  forstream-live:
    image: "forstream-live:latest"
    container_name: "forstream-live"
    volumes:
      - "./configs.yml:/usr/src/forstream-live/configs.yml"
    ports:
      - "5000:5000"
      - "1935:1935"
networks:
  default:
    external:
      name: "forstream"
